from pathlib import Path

configfile: "example.yaml"

INPUT_PATH = config["pathvars"]["input_loc"]
SAMPLES = [i.stem for i in Path(INPUT_PATH).iterdir() if i.suffix == ".json"]
SMALL_SAMPLES = SAMPLES[0:5]
  



rule some:
  input:
    expand("<output_loc>/{sample}/xmove/out.json", sample=SMALL_SAMPLES)



rule all:
  input:
    expand("<output_loc>/{sample}/pull/gx/out.png", sample=SAMPLES)


rule rejig:
  input:
    expand("<input_loc>/{sample}.json", sample=SAMPLES)
  shell:
    "touch {input}"




rule rotate:
  input:
    "<input_loc>/{sample}.json"
  output:
    "<output_loc>/{sample}/rotate/out.json"
  log:
    "<output_loc>/{sample}/rotate/out.log"
  shell:
    "uv run preproc rotate {input} {output} 2>{log}"


rule ortho:
  input:
    "<output_loc>/{sample}/rotate/out.json"
  output:
    "<output_loc>/{sample}/ortho/out.json"
  log:
    "<output_loc>/{sample}/ortho/out.log"
  shell:
    "uv run preproc ortho {input} {output} 2>{log}"


rule simplify:
  input:
    "<output_loc>/{sample}/ortho/out.json"
  output:
    "<output_loc>/{sample}/simplify/out.json"
  log:
    "<output_loc>/{sample}/simplify/out.log"
  shell:
    "uv run preproc simplify {input} {output} 2>{log}"


rule xplan:
  input:
    "<output_loc>/{sample}/simplify/out.json"
  output:
    "<output_loc>/{sample}/xplan/out.png",
    "<output_loc>/{sample}/xplan/out.json"
  log:
    "<output_loc>/{sample}/xplan/out.log"
  shell:
    "uv run preproc xplan {input} {output} 2>{log}"

rule xmove:
  input:
    "<output_loc>/{sample}/xplan/out.json"
  output:
    "<output_loc>/{sample}/xmove/out.png",
    "<output_loc>/{sample}/xmove/out.json"
  log:
    "<output_loc>/{sample}/xmove/out.log"
  shell:
    "uv run preproc xmove {input} {output} 2>{log}"

rule test:
  shell:
    "uv run preproc welcome"
